app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    
     path("", views.MainIndexView.as_view(), name="index"),
     path("Dashboard", views.IndexView.as_view(), name="Dashboard"),
     path("chart/", views.ChartjsView.as_view(), name="chartjs"),
     path("buttons/", views.ButtonsView.as_view(), name="buttons"),
     path("typography/", views.TypographyView.as_view(), name="typography"),
     path("icons/", views.IconsView.as_view(), name="icons"),
     path("forms/", views.FormsView.as_view(), name="forms"),
     path("table/", views.TableView.as_view(), name="tables"),
     path("blankPage/", views.BlankPageView.as_view(), name="Blank_Page"),
     path("404/", views.Error404View.as_view(), name="error404"),
     path("500/", views.Error500View.as_view(), name="error500"),

     path("book_create/", views.BookCreateView.as_view(), name="book_create"),
     path("book_list/", views.BookList.as_view(), name="book_list"),
     path("book_table/", views.BookTableView.as_view(), name="book_table"),
     path("book_detial/<str:pk>/", views.BookDetialView.as_view(), name="book_detial"),
     path("book_update/<str:pk>/", views.BookUpdateView.as_view(), name="book_update"),
     path("book_delete/<str:pk>/", views.BookDeleteView.as_view(), name="book_delete"),

     path("auther_create/", views.AutherCreateView.as_view(), name="auther_create"),
     path("auther_list/", views.AutherListView.as_view(), name="auther_list"),
     path("auther_detial/<str:pk>/", views.AuthorDetialView.as_view(), name="auther_detial"),
     path("auther_update/<str:pk>/", views.AuthorUpdateView.as_view(), name="auther_update"),
     path("auther_delete/<str:pk>/", views.AuthorDeleteView.as_view(), name="auther_delete"),

     path("user_create/", views.UserCreateView.as_view(), name="user_create"),
     path("user_list/", views.UserListView.as_view(), name="user_list"),
     # path("user_detial/<str:pk>/", views.AuthorDetialView.as_view(), name="auther_detial"),
     path("user_update/<str:pk>/", views.UserUpdateView.as_view(), name="user_update"),
     path("user_delete/<str:pk>/", views.UserDeleteView.as_view(), name="user_delete"),
]

elibrary/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = ([
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path('accounts/', include('registration.backends.default.urls')),
]
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

templates/app/auther_views/createview.html
{% extends 'app/base.html' %} {% load static %} {% block content %}

{% load static i18n crispy_forms_tags %}
{% block title %}{{object}}{% endblock %}


{{form.media}}


<div class="bg-lamiiz-color">
    <form class="forms-sample container-fluid mt-5 col-11" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-gradient-primary mr-2">{% trans "Save" %}</button>
        <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "Cancel" %}</button>
    </form>
</div>
<style>
    .bg-lamiiz-color{
        background-color: #dcddde;
    }
</style>
{% endblock %}

templates/app/auther_views/deleteview.html
{% extends 'app/base.html' %}
{% load static i18n crispy_forms_tags  %}


{% block content %}

<div class="page-header">
  <h3 class="page-title"> Delete "{{object}}"</h3>
</div>

<div class="row">
  <div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <form method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
          <div class="buttons mt-5">
            <button type="submit" class="btn btn-gradient-danger">{% trans "Yes, Delete." %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "No, Take me back" %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/app/auther_views/detialview.html
{% extends 'app/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}

{% block content %}

<div class="page-header">
  <h3 class="page-title">{{object}}</h3>
</div>

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">{{object.title}}</h4>
          </div>
            <div class="card-body">
              <div>
             
              </div>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <tbody>

                            <tr>
                              <td> {{object.name}} </td>
                              <td> {{object.bio|slice:60}}... </td>
                              

                            </tr>

                        </tbody>
                        
                    </table>

                </div>
            </div>
            <div class="card-footer">
              <div class="">
                <a href="{{object.get_update_url}}" class="btn btn-sm btn-light btn-outline-info mr-2">{% trans "Edit" %}</a>
                <a href="{{object.get_delete_url}}" class="btn btn-sm btn-light btn-outline-danger">{% trans "Delete" %}</a>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/app/auther_views/listview.html
{% extends 'app/base.html' %} 

{% load static i18n crispy_forms_tags %}

{% block content %}
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
            <i class="mdi mdi-home"></i>
        </span> {{title}}
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'app:auther_create' %}" class="btn btn-lg btn-gradient-primary">New {{title}}</a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th class="fw-bold"> number </th>
                                <th class="fw-bold"> name </th>
                                <th class="fw-bold"> bio </th>
                               
                                {% if request.user.is_superuser %}<th> Actions </th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.name}} </td>
                                <td> {{object.bio|slice:60}}... </td>

                                {% if request.user.is_superuser %}
                                <td>
                                    <a href="{{object.get_absolute_url}}" class="btn btn-sm btn-circle btn-primary"><i class="mdi mdi-account-card-details"></i></a>
                                    <a href="{{object.get_update_url}}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{{object.get_delete_url}}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                                {% endif %}
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% comment %} {% else %}
                <small class="mb-0">No {% get_verbose_name object_list.0 %} exists.</small> {% endcomment %}
                {% endif %}
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/app/auther_views/updateview.html
{% extends 'app/base.html' %} {% load static %} {% block content %}

{% load static i18n crispy_forms_tags %}
{% block title %}{{object}}{% endblock %}


{{form.media}}


<div class="bg-lamiiz-color">
    <form class="forms-sample container-fluid mt-5 col-lg-11" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-gradient-primary mr-2">{% trans "Save" %}</button>
        <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "Cancel" %}</button>
    </form>
</div>
<style>
    .bg-lamiiz-color{
        background-color: #dcddde;
    }
</style>
{% endblock %}