app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    
     path("", views.MainIndexView.as_view(), name="index"),
     path("Dashboard", views.IndexView.as_view(), name="Dashboard"),
     path("chart/", views.ChartjsView.as_view(), name="chartjs"),
     path("buttons/", views.ButtonsView.as_view(), name="buttons"),
     path("typography/", views.TypographyView.as_view(), name="typography"),
     path("icons/", views.IconsView.as_view(), name="icons"),
     path("forms/", views.FormsView.as_view(), name="forms"),
     path("table/", views.TableView.as_view(), name="tables"),
     path("blankPage/", views.BlankPageView.as_view(), name="Blank_Page"),
     path("404/", views.Error404View.as_view(), name="error404"),
     path("500/", views.Error500View.as_view(), name="error500"),

     path("book_create/", views.BookCreateView.as_view(), name="book_create"),
     path("book_list/", views.BookList.as_view(), name="book_list"),
     path("book_table/", views.BookTableView.as_view(), name="book_table"),
     path("book_detial/<str:pk>/", views.BookDetialView.as_view(), name="book_detial"),
     path("book_update/<str:pk>/", views.BookUpdateView.as_view(), name="book_update"),
     path("book_delete/<str:pk>/", views.BookDeleteView.as_view(), name="book_delete"),

     path("auther_create/", views.AutherCreateView.as_view(), name="auther_create"),
     path("auther_list/", views.AutherListView.as_view(), name="auther_list"),
     path("auther_detial/<str:pk>/", views.AuthorDetialView.as_view(), name="auther_detial"),
     path("auther_update/<str:pk>/", views.AuthorUpdateView.as_view(), name="auther_update"),
     path("auther_delete/<str:pk>/", views.AuthorDeleteView.as_view(), name="auther_delete"),

     path("user_create/", views.UserCreateView.as_view(), name="user_create"),
     path("user_list/", views.UserListView.as_view(), name="user_list"),
     # path("user_detial/<str:pk>/", views.AuthorDetialView.as_view(), name="auther_detial"),
     path("user_update/<str:pk>/", views.UserUpdateView.as_view(), name="user_update"),
     path("user_delete/<str:pk>/", views.UserDeleteView.as_view(), name="user_delete"),
]

elibrary/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = ([
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path('accounts/', include('registration.backends.default.urls')),
]
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

templates/app/partials/_footer.html
<footer class="footer">
  <div class="container-fluid d-flex justify-content-between">
    <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
    <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
  </div>
</footer>

templates/app/partials/_navbar.html
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="{% url 'app:index' %}"><img src="/static/app/images/logo.svg"
        alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="{% url 'app:index' %}"><img src="/static/app/images/logo-mini.svg"
        alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    <div class="search-field d-none d-md-block">
      <form class="d-flex align-items-center h-100" action="#">
        <div class="input-group">
          <div class="input-group-prepend bg-transparent">
            <i class="input-group-text border-0 mdi mdi-magnify"></i>
          </div>
          <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
        </div>
      </form>
    </div>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown"
          aria-expanded="false">
          <div class="nav-profile-img">
            <img src="/static/app/images/faces/face1.jpg" alt="image">
            <span class="availability-status online"></span>
          </div>
          <div class="nav-profile-text">
            <p class="mb-1 text-black">{{user.username}}</p>
          </div>
        </a>

        
        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
          <a class="dropdown-item lamiiz-hover" id="refreshButton" href="#"><i class="mdi mdi-cached me-2 text-success"></i> refresh page </a> 

          <div class="dropdown-divider">
          </div>
          <a class="dropdown-item lamiiz-hover" href="{% url 'registration_register' %} "><i
              class="mdi mdi-cached me-2 text-success"></i> Register </a>
          {% if request.user.is_authenticated %}
          <a class="dropdown-item lamiiz-hover" href="{% url 'auth_logout' %}">
            <i class="mdi mdi-logout me-2 text-primary"></i> Signout </a>
          <a class="dropdown-item lamiiz-hover" href="{% url 'auth_password_change' %}"><i
              class="mdi mdi-cached me-2 text-success"></i> Change Passsword </a>
          {% else %}
          <a class="dropdown-item lamiiz-hover" href="{% url 'auth_login' %}">
            <i class="mdi mdi-logout me-2 text-primary"></i> Login </a>
          {% endif %}

        </div>
      </li>
      <li class="nav-item d-none d-lg-block full-screen-link">
        <a class="nav-link">
          <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-bs-toggle="dropdown"
          aria-expanded="false">
          <i class="mdi mdi-email-outline"></i>
          <span class="count-symbol bg-warning"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
          <h6 class="p-3 mb-0">Messages</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="/static/app/images/faces/face4.jpg" alt="image" class="profile-pic">
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
              <p class="text-gray mb-0"> 1 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="/static/app/images/faces/face2.jpg" alt="image" class="profile-pic">
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
              <p class="text-gray mb-0"> 15 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="/static/app/images/faces/face3.jpg" alt="image" class="profile-pic">
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
              <p class="text-gray mb-0"> 18 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <h6 class="p-3 mb-0 text-center">4 new messages</h6>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#"
          data-bs-toggle="dropdown">
          <i class="mdi mdi-bell-outline"></i>
          <span class="count-symbol bg-danger"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
          aria-labelledby="notificationDropdown">
          <h6 class="p-3 mb-0">Notifications</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-success">
                <i class="mdi mdi-calendar"></i>
              </div>
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
              <p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-warning">
                <i class="mdi mdi-settings"></i>
              </div>
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
              <p class="text-gray ellipsis mb-0"> Update dashboard </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-info">
                <i class="mdi mdi-link-variant"></i>
              </div>
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
              <p class="text-gray ellipsis mb-0"> New admin wow! </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <h6 class="p-3 mb-0 text-center">See all notifications</h6>
        </div>
      </li>
      <li class="nav-item nav-logout d-none d-lg-block">
        <a class="nav-link" href="#" onclick="closeWindow()">
          <i class="mdi mdi-power"></i>
        </a>
      </li>
      <li class="nav-item nav-settings d-none d-lg-block">
        <a class="nav-link" href="#">
          <i class="mdi mdi-format-line-spacing"></i>
        </a>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
      data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

templates/app/partials/_proBanner.html
<div class="row p-0 m-0 proBanner" id="proBanner">
    <div class="col-md-12 p-0 m-0">
      <div class="card-body card-body-padding d-flex align-items-center justify-content-between">
        <div class="ps-lg-1">
          <div class="d-flex align-items-center justify-content-between">
            <p class="mb-0 font-weight-medium me-3 buy-now-text">Free 24/7 customer support, updates, and more with
              this template!</p>
            <a href="https://www.bootstrapdash.com/product/purple-bootstrap-admin-template/?utm_source=organic&utm_medium=banner&utm_campaign=buynow_demo"
              target="_blank" class="btn me-2 buy-now-btn border-0">Get Pro</a>
          </div>
        </div>
        <div class="d-flex align-items-center justify-content-between">
          <a href="https://www.bootstrapdash.com/product/purple-bootstrap-admin-template/"><i
              class="mdi mdi-home me-3 text-white"></i></a>
          <button id="bannerClose" class="btn border-0 p-0">
            <i class="mdi mdi-close text-white me-0"></i>
          </button>
        </div>
      </div>
    </div>
  </div>

templates/app/partials/_sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <a href="#" class="nav-link">
        <div class="nav-profile-image">
          <img src="/static/app/images/faces/face1.jpg" alt="profile">
          <span class="login-status online"></span>
          <!--change to offline or busy as needed-->
        </div>
        <div class="nav-profile-text d-flex flex-column">
          <span class="font-weight-bold mb-2">{{user.username}}</span>
          <span class="text-secondary text-small"><small>{{user.email}}</small></span>
        </div>
        <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:index' %}">
        <span class="menu-title">Dashboard</span>
        <i class="mdi mdi-home menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:book_list' %}">
        <span class="menu-title">Book list</span>
        <i class="mdi mdi-playlist-plus menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:auther_list' %}">
        <span class="menu-title">Auther list</span>
        <i class="mdi mdi-account-multiple-plus menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:user_list' %}">
        <span class="menu-title">user list</span>
        <i class="mdi mdi-account-multiple-plus menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <span class="menu-title">Basic UI Elements</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-crosshairs-gps menu-icon"></i>
      </a>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{% url 'app:buttons' %}">Buttons</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'app:typography' %}">Typography</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:icons' %}">
        <span class="menu-title">Icons</span>
        <i class="mdi mdi-contacts menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:forms' %}">
        <span class="menu-title">Forms</span>
        <i class="mdi mdi-format-list-bulleted menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:chartjs' %}">
        <span class="menu-title">Charts</span>
        <i class="mdi mdi-chart-bar menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app:tables' %}">
        <span class="menu-title">Tables</span>
        <i class="mdi mdi-table-large menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#general-pages" aria-expanded="false" aria-controls="general-pages">
        <span class="menu-title">Sample Pages</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-medical-bag menu-icon"></i>
      </a>
      <div class="collapse" id="general-pages">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{% url 'app:Blank_Page' %}"> Blank Page </a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'auth_login' %}"> Login </a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'registration_register' %}"> Register </a></li>
          <!-- <li class="nav-item"> <a class="nav-link" href="{% url 'app:error404' %}"> 404 </a></li> -->
          <!-- <li class="nav-item"> <a class="nav-link" href="{% url 'app:error500' %}"> 500 </a></li> -->
          <li class="nav-item"> <a class="nav-link" href="{% url 'app:book_create' %}"> Book Create </a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'app:book_list' %}"> Book List </a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item sidebar-actions">
      <span class="nav-link">
        <div class="border-bottom">
          <h6 class="font-weight-normal mb-3">Projects</h6>
        </div>
        <button class="btn btn-block btn-lg btn-gradient-primary mt-4">+ Add a project</button>
        <div class="mt-4">
          <div class="border-bottom">
            <p class="text-secondary">Categories</p>
          </div>
          <ul class="gradient-bullet-list mt-4">
            <li>Free</li>
            <li>Pro</li>
          </ul>
        </div>
      </span>
    </li>
  </ul>
</nav>